/* AUTO-GENERATED: api.ts — do not edit by hand. */

import type { AxiosRequestConfig } from "axios";
import { getRpcClient } from "../base";
import type { Login_Params, Login_Result, Logout_Params, Logout_Result, GetSessionStatus_Params, GetSessionStatus_Result, RdsBillingTariff_Create_Params, RdsBillingTariff_Create_Result, RdsBillingTariff_Update_Params, RdsBillingTariff_Update_Result, RdsBillingTariff_Delete_Params, RdsBillingTariff_Delete_Result, RdsBillingTariff_GetAll_Params, RdsBillingTariff_GetAll_Result, Dodavatel_Create_Params, Dodavatel_Create_Result, Dodavatel_Update_Params, Dodavatel_Update_Result, Dodavatel_Delete_Params, Dodavatel_Delete_Result, Dodavatel_GetAll_Params, Dodavatel_GetAll_Result, InvoiceItem_Create_Params, InvoiceItem_Create_Result, InvoiceItem_Update_Params, InvoiceItem_Update_Result, InvoiceItem_Delete_Params, InvoiceItem_Delete_Result, InvoiceItemRevision_Create_Params, InvoiceItemRevision_Create_Result, InvoiceItemRevision_Update_Params, InvoiceItemRevision_Update_Result, InvoiceItemRevision_Delete_Params, InvoiceItemRevision_Delete_Result, Mds_Create_Params, Mds_Create_Result, Mds_Update_Params, Mds_Update_Result, Mds_Delete_Params, Mds_Delete_Result, Mds_GetAll_Params, Mds_GetAll_Result, Mds_GetByEic_Params, Mds_GetByEic_Result, MdsPurgeById_Params, MdsPurgeById_Result, MdsRevision_Create_Params, MdsRevision_Create_Result, MdsRevision_Update_Params, MdsRevision_Update_Result, MdsRevision_Delete_Params, MdsRevision_Delete_Result, Oom_Create_Params, Oom_Create_Result, Oom_Update_Params, Oom_Update_Result, Oom_Delete_Params, Oom_Delete_Result, OomGetByEic_Params, OomGetByEic_Result, OomGetByMdsId_Params, OomGetByMdsId_Result, OomRevision_InsertNewRevision_Params, OomRevision_InsertNewRevision_Result, OomRevision_Create_Params, OomRevision_Create_Result, OomRevision_Update_Params, OomRevision_Update_Result, OomRevision_Delete_Params, OomRevision_Delete_Result } from "./types";

export const api = {
  Login: (params: Login_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Login_Params, Login_Result>("Login", params, axios),
  Logout: (params: Logout_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Logout_Params, Logout_Result>("Logout", params, axios),
  GetSessionStatus: (params: GetSessionStatus_Params, axios?: AxiosRequestConfig) => getRpcClient().call<GetSessionStatus_Params, GetSessionStatus_Result>("GetSessionStatus", params, axios),
  RdsBillingTariff_Create: (params: RdsBillingTariff_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<RdsBillingTariff_Create_Params, RdsBillingTariff_Create_Result>("RdsBillingTariff_Create", params, axios),
  RdsBillingTariff_Update: (params: RdsBillingTariff_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<RdsBillingTariff_Update_Params, RdsBillingTariff_Update_Result>("RdsBillingTariff_Update", params, axios),
  RdsBillingTariff_Delete: (params: RdsBillingTariff_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<RdsBillingTariff_Delete_Params, RdsBillingTariff_Delete_Result>("RdsBillingTariff_Delete", params, axios),
  RdsBillingTariff_GetAll: (params: RdsBillingTariff_GetAll_Params, axios?: AxiosRequestConfig) => getRpcClient().call<RdsBillingTariff_GetAll_Params, RdsBillingTariff_GetAll_Result>("RdsBillingTariff_GetAll", params, axios),
  Dodavatel_Create: (params: Dodavatel_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Dodavatel_Create_Params, Dodavatel_Create_Result>("Dodavatel_Create", params, axios),
  Dodavatel_Update: (params: Dodavatel_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Dodavatel_Update_Params, Dodavatel_Update_Result>("Dodavatel_Update", params, axios),
  Dodavatel_Delete: (params: Dodavatel_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Dodavatel_Delete_Params, Dodavatel_Delete_Result>("Dodavatel_Delete", params, axios),
  Dodavatel_GetAll: (params: Dodavatel_GetAll_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Dodavatel_GetAll_Params, Dodavatel_GetAll_Result>("Dodavatel_GetAll", params, axios),
  InvoiceItem_Create: (params: InvoiceItem_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<InvoiceItem_Create_Params, InvoiceItem_Create_Result>("InvoiceItem_Create", params, axios),
  InvoiceItem_Update: (params: InvoiceItem_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<InvoiceItem_Update_Params, InvoiceItem_Update_Result>("InvoiceItem_Update", params, axios),
  InvoiceItem_Delete: (params: InvoiceItem_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<InvoiceItem_Delete_Params, InvoiceItem_Delete_Result>("InvoiceItem_Delete", params, axios),
  InvoiceItemRevision_Create: (params: InvoiceItemRevision_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<InvoiceItemRevision_Create_Params, InvoiceItemRevision_Create_Result>("InvoiceItemRevision_Create", params, axios),
  InvoiceItemRevision_Update: (params: InvoiceItemRevision_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<InvoiceItemRevision_Update_Params, InvoiceItemRevision_Update_Result>("InvoiceItemRevision_Update", params, axios),
  InvoiceItemRevision_Delete: (params: InvoiceItemRevision_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<InvoiceItemRevision_Delete_Params, InvoiceItemRevision_Delete_Result>("InvoiceItemRevision_Delete", params, axios),
  Mds_Create: (params: Mds_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Mds_Create_Params, Mds_Create_Result>("Mds_Create", params, axios),
  Mds_Update: (params: Mds_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Mds_Update_Params, Mds_Update_Result>("Mds_Update", params, axios),
  Mds_Delete: (params: Mds_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Mds_Delete_Params, Mds_Delete_Result>("Mds_Delete", params, axios),
  Mds_GetAll: (params: Mds_GetAll_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Mds_GetAll_Params, Mds_GetAll_Result>("Mds_GetAll", params, axios),
  Mds_GetByEic: (params: Mds_GetByEic_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Mds_GetByEic_Params, Mds_GetByEic_Result>("Mds_GetByEic", params, axios),
  MdsPurgeById: (params: MdsPurgeById_Params, axios?: AxiosRequestConfig) => getRpcClient().call<MdsPurgeById_Params, MdsPurgeById_Result>("MdsPurgeById", params, axios),
  MdsRevision_Create: (params: MdsRevision_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<MdsRevision_Create_Params, MdsRevision_Create_Result>("MdsRevision_Create", params, axios),
  MdsRevision_Update: (params: MdsRevision_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<MdsRevision_Update_Params, MdsRevision_Update_Result>("MdsRevision_Update", params, axios),
  MdsRevision_Delete: (params: MdsRevision_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<MdsRevision_Delete_Params, MdsRevision_Delete_Result>("MdsRevision_Delete", params, axios),
  Oom_Create: (params: Oom_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Oom_Create_Params, Oom_Create_Result>("Oom_Create", params, axios),
  Oom_Update: (params: Oom_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Oom_Update_Params, Oom_Update_Result>("Oom_Update", params, axios),
  Oom_Delete: (params: Oom_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<Oom_Delete_Params, Oom_Delete_Result>("Oom_Delete", params, axios),
  OomGetByEic: (params: OomGetByEic_Params, axios?: AxiosRequestConfig) => getRpcClient().call<OomGetByEic_Params, OomGetByEic_Result>("OomGetByEic", params, axios),
  OomGetByMdsId: (params: OomGetByMdsId_Params, axios?: AxiosRequestConfig) => getRpcClient().call<OomGetByMdsId_Params, OomGetByMdsId_Result>("OomGetByMdsId", params, axios),
  OomRevision_InsertNewRevision: (params: OomRevision_InsertNewRevision_Params, axios?: AxiosRequestConfig) => getRpcClient().call<OomRevision_InsertNewRevision_Params, OomRevision_InsertNewRevision_Result>("OomRevision_InsertNewRevision", params, axios),
  OomRevision_Create: (params: OomRevision_Create_Params, axios?: AxiosRequestConfig) => getRpcClient().call<OomRevision_Create_Params, OomRevision_Create_Result>("OomRevision_Create", params, axios),
  OomRevision_Update: (params: OomRevision_Update_Params, axios?: AxiosRequestConfig) => getRpcClient().call<OomRevision_Update_Params, OomRevision_Update_Result>("OomRevision_Update", params, axios),
  OomRevision_Delete: (params: OomRevision_Delete_Params, axios?: AxiosRequestConfig) => getRpcClient().call<OomRevision_Delete_Params, OomRevision_Delete_Result>("OomRevision_Delete", params, axios),
} as const;
